CREATE TABLE sequencing_run_illumina (
  pk SERIAL PRIMARY KEY,
  sequencing_run_id VARCHAR(255) UNIQUE NOT NULL,
  flowcell_id VARCHAR(255),
  instrument_id VARCHAR(255),
  experiment_name VARCHAR(255),
  run_date DATE,
  cluster_density FLOAT,
  cluster_density_passed_filter FLOAT,
  percent_occupied FLOAT,
  error_rate FLOAT,
  first_cycle_intensity FLOAT,
  num_cycles_r1 INTEGER,
  num_cycles_r2 INTEGER,
  num_reads INTEGER,
  num_reads_passed_filter INTEGER,
  percent_reads_passed_filter FLOAT,
  percent_aligned FLOAT,
  q30_percent FLOAT,
  projected_yield_gigabases FLOAT,
  yield_gigabases FLOAT,
  CONSTRAINT fk_sequencing_instrument_illumina FOREIGN KEY(instrument_id) REFERENCES sequencing_instrument_illumina(instrument_id)
);
