CREATE TABLE sequencing_run_illumina (
  pk BIGSERIAL PRIMARY KEY,
  sequencing_run_id VARCHAR(255) UNIQUE NOT NULL,
  flowcell_id VARCHAR(255),
  instrument_id VARCHAR(255),
  experiment_name VARCHAR(255),
  run_date DATE,
  cluster_density REAL,
  cluster_density_passed_filter REAL,
  percent_occupied REAL,
  error_rate REAL,
  first_cycle_intensity REAL,
  num_cycles_r1 INTEGER,
  num_cycles_r2 INTEGER,
  num_reads BIGINT,
  num_reads_passed_filter BIGINT,
  percent_reads_passed_filter REAL,
  percent_aligned REAL,
  q30_percent REAL,
  projected_yield_gigabases REAL,
  yield_gigabases REAL,
  CONSTRAINT ck_cluster_density_positive CHECK (cluster_density > 0),
  CONSTRAINT ck_cluster_density_passed_filter_positive CHECK (cluster_density_passed_filter > 0),
  CONSTRAINT ck_cluster_density_ordered CHECK (cluster_density >= cluster_density_passed_filter),
  CONSTRAINT ck_percent_occupied_percentage CHECK (percent_occupied BETWEEN 0 AND 100),
  CONSTRAINT ck_error_rate_percentage CHECK (error_rate BETWEEN 0 AND 100),
  CONSTRAINT ck_first_cycle_intensity_positive CHECK (first_cycle_intensity > 0),
  CONSTRAINT ck_num_cycles_r1_positive CHECK (num_cycles_r1 > 0),
  CONSTRAINT ck_num_cycles_r2_positive CHECK (num_cycles_r2 > 0),
  CONSTRAINT ck_num_reads_positive CHECK (num_reads > 0),
  CONSTRAINT ck_num_reads_passed_filter_positive CHECK (num_reads_passed_filter > 0),
  CONSTRAINT ck_num_reads_ordered CHECK (num_reads >= num_reads_passed_filter),
  CONSTRAINT ck_percent_reads_passed_filter_percentage CHECK (percent_reads_passed_filter BETWEEN 0 AND 100),
  CONSTRAINT ck_percent_aligned_percentage CHECK (percent_aligned BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_percentage CHECK (q30_percent BETWEEN 0 AND 100),
  CONSTRAINT ck_projected_yield_gigabases_positive CHECK (projected_yield_gigabases > 0),
  CONSTRAINT ck_yield_gigabases_positive CHECK (yield_gigabases > 0)
);
