CREATE TABLE sequenced_library_illumina (
  pk SERIAL PRIMARY KEY,
  library_id VARCHAR(255) NOT NULL,
  sample_number INTEGER,
  demultiplexing_fk INTEGER,
  project_id_samplesheet VARCHAR(255),
  project_id_translated VARCHAR(255),
  fastq_filename_r1 VARCHAR(255),
  fastq_file_size_mb_r1 NUMERIC,
  fastq_md5_r1 VARCHAR(255),
  fastq_filename_r2 VARCHAR(255),
  fastq_file_size_mb_r2 NUMERIC,
  fastq_md5_r2 VARCHAR(255),
  index VARCHAR(255),
  index2 VARCHAR(255),
  num_reads INTEGER,
  num_bases INTEGER,
  q30_percent NUMERIC,
  q30_percent_last_25_bases NUMERIC,
  q30_percent_r1 NUMERIC,
  q30_percent_last_25_bases_r1 NUMERIC,
  q30_percent_r2 NUMERIC,
  q30_percent_last_25_bases_r2 NUMERIC,

  CONSTRAINT fk_demultiplexing FOREIGN KEY(demultiplexing_fk) REFERENCES sequencing_run_illumina_demultiplexing(pk)
);
