CREATE TABLE sequenced_library_illumina (
  pk BIGSERIAL PRIMARY KEY,
  library_id VARCHAR(255) NOT NULL,
  sample_number INTEGER,
  demultiplexing_fk BIGINT NOT NULL,
  project_id_samplesheet VARCHAR(255),
  project_id_translated VARCHAR(255),
  fastq_filename_r1 VARCHAR(255),
  fastq_file_size_mb_r1 REAL,
  fastq_md5_r1 VARCHAR(255),
  fastq_filename_r2 VARCHAR(255),
  fastq_file_size_mb_r2 REAL,
  fastq_md5_r2 VARCHAR(255),
  index VARCHAR(255),
  index2 VARCHAR(255),
  num_reads BIGINT,
  num_bases BIGINT,
  q30_percent REAL,
  q30_percent_last_25_bases REAL,
  q30_percent_r1 REAL,
  q30_percent_last_25_bases_r1 REAL,
  q30_percent_r2 REAL,
  q30_percent_last_25_bases_r2 REAL,
  CONSTRAINT fk_demultiplexing FOREIGN KEY(demultiplexing_fk) REFERENCES sequencing_run_illumina_demultiplexing(pk) ON DELETE CASCADE,
  CONSTRAINT uq_sequenced_library_per_demux UNIQUE (library_id, sample_number, demultiplexing_fk),
  CONSTRAINT ck_sample_number_positive CHECK (sample_number > 0),
  CONSTRAINT ck_num_reads_positive CHECK (num_reads > 0),
  CONSTRAINT ck_num_bases_positive CHECK (num_bases > 0),
  CONSTRAINT ck_fastq_file_size_mb_r1_positive CHECK (fastq_file_size_mb_r1 > 0),
  CONSTRAINT ck_fastq_file_size_mb_r2_positive CHECK (fastq_file_size_mb_r2 > 0),
  CONSTRAINT ck_q30_percent_percentage CHECK (q30_percent BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_last_25_bases_percentage CHECK (q30_percent_last_25_bases BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_r1_percentage CHECK (q30_percent_r1 BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_last_25_bases_r1_percentage CHECK (q30_percent_last_25_bases_r1 BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_r2_percentage CHECK (q30_percent_r2 BETWEEN 0 AND 100),
  CONSTRAINT ck_q30_percent_last_25_bases_r2_percentage CHECK (q30_percent_last_25_bases_r2 BETWEEN 0 AND 100)
);
