name: "Test migrations"
on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SQLFLUFF_DIALECT: postgres
  DOCKER_IMAGE: flyway/flyway:9.21
  SCHEMAS: public

jobs:
  test_migrations:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Setup PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v4
    - name: Create Database
      run: >-
        ./.github/scripts/create_database.sh
    - name: Setup Flyway
      run: >-
        wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.21.2/flyway-commandline-9.21.2-linux-x64.tar.gz
        tar -xzf flyway-commandline-9.21.2-linux-x64.tar.gz
        ln -s `pwd`/flyway-9.21.2/flyway /usr/local/bin
    - name: Flyway Migrate
      run: >-
        ./.github/scripts/apply_migraions.sh
    - uses: actions/upload-artifact@v1
      with:
        name: report
        path: report.html